# Generated by Django 5.1.2 on 2024-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_tutor_profile_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='age',
        ),
        migrations.AddField(
            model_name='tutor',
            name='experienceYears',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лет опыта'),
        ),
    ]
