# Generated by Django 5.1.2 on 2025-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='paymentMethod',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
    ]
