# Generated by Django 5.1.2 on 2025-02-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0006_tutor_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='peopleReacted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общий рейтинг'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='totalRating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общий рейтинг'),
        ),
    ]
