# Generated by Django 5.1.2 on 2024-10-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_datetime',
            new_name='datetime',
        ),
    ]
