# Generated by Django 5.1.2 on 2024-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_service', '0002_rename_bid_amount_bid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
