# Generated by Django 5.1.2 on 2024-11-22 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('isConfirmed', models.BooleanField(blank=True, null=True)),
                ('confirmationTime', models.DateTimeField(blank=True, null=True)),
                ('isCancelled', models.BooleanField(blank=True, null=True)),
                ('cancellationTime', models.DateTimeField(blank=True, null=True)),
                ('isConducted', models.BooleanField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
