# Generated by Django 5.1.2 on 2024-11-22 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cancellationTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отмены'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='confirmationTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='isCancelled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отменено'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='isConducted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Проведено'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='isConfirmed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Репетитор'),
        ),
    ]
