# Generated by Django 5.1.2 on 2024-11-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0004_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date_start'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конца занятия'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала занятия'),
        ),
    ]
