# Generated by Django 5.1.2 on 2024-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0005_alter_lesson_options_remove_lesson_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
