# Generated by Django 5.1.2 on 2025-02-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0007_subject_alter_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='price',
        ),
    ]
