# Generated by Django 5.1.2 on 2025-02-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0008_remove_subject_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('conducted', 'Conducted')], default='awaiting_confirmation', max_length=25, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления статуса')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lesson_service.lesson', verbose_name='Занятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_participants', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник занятия',
                'verbose_name_plural': 'Участники занятий',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
