# Generated by Django 5.1.2 on 2025-02-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0009_lessonparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cancellationTime',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='confirmationTime',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='isCancelled',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='isConducted',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='isConfirmed',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
    ]
