# Generated by Django 5.1.2 on 2025-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_service', '0010_alter_lesson_options_remove_lesson_cancellationtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonparticipant',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка занятия'),
        ),
    ]
